name: Rust build and lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        toolchain: "x86_64-unknown-linux-gnu"
#    args: # optional
    - run: |
           rustup update
    - run: cargo update
    - name: Build
      run: cargo build --verbose
    - name: linting
      run: |
           rustup component add rustfmt
           cargo fmt
