name: Rust build and lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
           cargo -V
           rustc -V
    #- name: Build
     # run: cargo build --verbose
    #- name: linting
     # run: |
      #     rustup component add rustfmt
       #    cargo fmt
